name: Testing CI-CD

on:
  push:
    branches:
      - dev-flight
      - staging-flight
      - main

env:
  # Dev environment variables
  DEV_BUILD_SCRIPT: npm run dev-build-android
  DEV_APK_PATH: android/app/build/outputs/apk/dev/release/app-dev-release.apk
  DEV_ARTIFACT_NAME: app-dev-release.apk
  DEV_ENV_FILE: .env.dev

  # Staging environment variables
  STAGING_BUILD_SCRIPT: npm run stage-build-android
  STAGING_APK_PATH: android/app/build/outputs/apk/stage/release/app-stage-release.apk
  STAGING_ARTIFACT_NAME: app-stage-release.apk
  STAGING_ENV_FILE: .env.stage

  # Production environment variables
  PROD_BUILD_SCRIPT: npm run live-build-android
  PROD_APK_PATH: android/app/build/outputs/apk/live/release/app-live-release.apk
  PROD_ARTIFACT_NAME: app-live-release.apk
  PROD_ENV_FILE: .env.live

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "${{ vars.LIVE_ENV }}" > ${{ env.PROD_ENV_FILE }}
            echo "BUILD_SCRIPT=${{ env.PROD_BUILD_SCRIPT }}" >> $GITHUB_ENV
            echo "APK_PATH=${{ env.PROD_APK_PATH }}" >> $GITHUB_ENV
            echo "ARTIFACT_NAME=${{ env.PROD_ARTIFACT_NAME }}" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" = "refs/heads/staging-flight" ]; then
            echo "${{ vars.STAGING_ENV }}" > ${{ env.STAGING_ENV_FILE }}
            echo "BUILD_SCRIPT=${{ env.STAGING_BUILD_SCRIPT }}" >> $GITHUB_ENV
            echo "APK_PATH=${{ env.STAGING_APK_PATH }}" >> $GITHUB_ENV
            echo "ARTIFACT_NAME=${{ env.STAGING_ARTIFACT_NAME }}" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" = "refs/heads/dev-flight" ]; then
            echo "${{ vars.DEV_ENV }}" > ${{ env.DEV_ENV_FILE }}
            echo "BUILD_SCRIPT=${{ env.DEV_BUILD_SCRIPT }}" >> $GITHUB_ENV
            echo "APK_PATH=${{ env.DEV_APK_PATH }}" >> $GITHUB_ENV
            echo "ARTIFACT_NAME=${{ env.DEV_ARTIFACT_NAME }}" >> $GITHUB_ENV
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Decode dev keystore
        if: always()
        run: |
          "MIIKwAIBAzCCCmoGCSqGSIb3DQEHAaCCClsEggpXMIIKUzCCBboGCSqGSIb3DQEHAaCCBasEggWnMIIFozCCBZ8GCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFCncuvqmQ0mRHF4NYCA1liChbcCjAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQb10Kytf49nUzRatfeI7SzASCBNDxs4jjIpazRRjzbjyLaHiOoBwaWN7jE5v0EyHSu7Sd/kNLkykHiwpowirvVgZKEXwqiGo5FWR60SxT2GCUcKmYCOcTdLRDLCIcwINSYfjxOUAXPaj6BJ3nKKRYZyFz8vuSVank+yyln9N9aHvzlIf9Llmrm/ILn04UxJe4XiXZDZGkr+ASOMDtwlRfSyQJFky4rA7U9KBgd4BZdLXf3c5SaaH1oGAS9zZYUVLxXwTTiXUyJ2T/zGxVGd3LCN0PEDgdGJOslnqMOXPY0/oVp1n18411J9vdyxOrJcqfq7GIXl8e7FpEdGvfEKiqvuZ9lBI7lKzmpxtXqqzMwU3i/90uWgjHGRBYQ9T4dvqA1OC+TtDo5imrv9jxzgLnvHIP9sfnoqQkmjqNz7ARp9lZktK9Q7poGbspLS/X4MINwAG/9H1ClrQ6jxeW8fjKxo9DlUjBlGwQ/lbzzXPueQjCLktFw6Hm+ielY5tKRDgwlHvyld6g6mbDFieGe23uG/NqPAF0DsitALmywifeaBj24ttnw+SMW03chVrB+uj9cQ5gMFyd2mUAoS/a6mlRRj6Fdvvszoiftdkexf3ztlSjabhfq04w9c0638pN+NFWuo4aoorjDFtHtbRSW6uRIRKwdTwFdJvu5kkWHgIC6zdCn3MdWm1M+9+TIGCaZj/cgoX5IPY5zf1O9Q4ZGg/culziO8wN+SknyMdDQoXBW70KrLCYoLcObMX5lGLL6q262XcWbcAoeGN244/xld4fSHX2tX0H8XTpkmPebeqCkjJ9ITLryC5KqhWnKZD/IGIULSql8Q76Xr1kRo4sdJL+4uHjg39duQYyqoBo8ErGqw37upO063vuq3YKlH+r1+/7w6F1heSZBFH5GaTFoShlIYWlE5kWQlIe7YxByGYUbg+D4oM8Am64afOTJkLUPqmUhlEuooxjySdD9jeoDnlBRbG4YRbnauKwxr7i0hzQZZ5k2x+KvsIowqloN8EbxzgwpSblVmB1nyotR4Qy2APDe+8ylI5Jr0iu4F/Q1WxajpyCa+0VjfnecAJVX3xBxiAlluXr72IX0mCP/Qs/GifEh7eMgt1gWmEKi7UtWIZhFoR0jI8Q6VrznquvzftU+1hKZMTHE3M7c8iXjtRaGNKoJKhOyvNEKbdM7zMAhHQlvXMwT3tu7msxomrO+Oh9g31TfygqnHWV1tzXX0nxyw7KqPdzk/8g4RPXn6vG3l4qP2GRnFcAVsBbRkDClowj402IOwwzxK45PKPhkzeF58SmlX0gHGgO0sUgv29oc4HHqjHlapJ31MhVGLhmaLapYQyqM4CPNyQF+oldWG8zeL8pdK9XQp3ObO+/fZA5gAXfNDym3YyHdyx7sVwrZm3evitXTpenb7wIaPLVW5BgZxu4defnCTJZcT0cvIRF1CuxJ9hFKBt1ANWrw0aCQfridDgmJH0u+GWyxF9QNSIbSxUz43Mv+vGXEQ/t9Q+D3K9RNbPzAZCJfemaXWCGLXFaLY7NHfaLf5JrQeml2LguFzGkLY1/YPQ8iiV3EcXtzpd9KkyJ7rkCCLXpiPk54VSC0GC3nWq611UnCOJUYZTRtmnLobcDsFKjyuRhbyrTrXPMhAs+to+AYYy6VlQhKaYcXkcUccTWtTFMMCcGCSqGSIb3DQEJFDEaHhgAbQB5AC0AawBlAHkALQBhAGwAaQBhAHMwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTc0ODI1MjA3MTAwNTCCBJEGCSqGSIb3DQEHBqCCBIIwggR+AgEAMIIEdwYJKoZIhvcNAQcBMGYGCSqGSIb3DQEFDTBZMDgGCSqGSIb3DQEFDDArBBQWFJ3PypXL2qU6klqXHsdVuOkMegICJxACASAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEFagyOR+XBQT8B5V6DDpjfOAggQAyUbhhZA7PjHnAdGe2n4gLV6PyYF6M7dx62YJgu9DIHzDsNn+CdzcyakXHBPjcenAWcOzkYTu6bWRJkJalPKFTG/ucgI8sxmi6xDD3tmNme9bqEf6SkLSbQQiKfIn4LXb27jRM9COi0fdSTajngnDwhsIkAnIPuuH4RbMygwm+C/nS8G0ambG8XR2A5bcQRzT/WXdyDI+K1CFDqXp8A6cm2TIr9jsHAeVVGWlKgjzbsZO7CYhEALY1FyIJcDpmgpIxiJHp9zoN4893m+N8WGU9tUdL9xa6CYvSjDyvzckU9blnnbIFoHM1OSNBggMzi82v5k3L0HOALCEN4rSew1Plwj4n6wc9WQvJnM1Er4Kn3PDmt9+J0eDef+NItfY9ozTLSgdY5kbRik1Wn69dURRAU9Agx9xJXv+n4R58qYjXTdoBZGDSx/IE+iRCxK477iAYTv6R+nCNvf6wxbEEtpY5/c2G+rkV9I1iHa6f6v0WeTw1myVXnJaDvUgq6dJEdDPx3ujWM0rQF3e4lkju+G/tj/DniAdHsbDnWEnb0u83ItLGVkexuUtEljL87NQ1ZFGJMIUzGZIJKN72rAP8PW0gzGAhNp0+pZJzB9/gSCeSV3jDzmSr4rBpWcJDZlMwKlqsVjS1hm0YpftWp2CQlEZSRorivavHFKNI4HZXCLI1yTReX8G29YwPby/A2sqpmwbtZJB8NewIPHv8UDaN6eP2HHa1W606sJU1qBxZdhTHyLb8LXnIklvFwWaMBV6ShFNcE/16B0xUZMQzuGEvEUr2HqpJBI0vU0Ip5Gro/JJ1ic14sYG3BH0c+cyC8ZcwwfqNr4mPt0SNznehQUCrQIhfPTz3f+RzPdu5WD6Bi9KvLS8cZoWAI9sf4RH6Q15sDedS7skgyEV87yWHa13a31MPi+Vf7SP6hGfXSuAT4qCOwS54PxDFKXMqPH54mOLU7vvXPGEtFriEECqTA0Z7GQvLZaHdql2mdT6NbFpjmNTMqsAfEHb6ZUklH0CoMkrrWCTBFRPAnCc28YP8uFz7GPZpB96GtWNQlxF7NLDBkBeMp+QCRJgXBgUlNL05/aZ+rxCCnbVwedgYt9pzBhYmgWHmCJCX7/8axBwYOoqdZavfIGYeYMllKbterDvN3ppdV8LXGXVR5/koUZYSbcMNF6dnhhtmsAE+Wul8UNxnIuJvX0htVzZs3NVu/SzTt4Th3kwgBtxxTDf/J7VE2tAeZm7QMkcBgUF/5mi6Yxylv6rVuQ062NRcMcqCU3FkWbVzmmVmdsWb0fz55tvAk+nfRZtfdZRqPllVD0qlvH/M/gNvqg4eKb0NqnFYVhB5yZYGqZI2M6LJrXY6I1QUho7o49j4jBNMDEwDQYJYIZIAWUDBAIBBQAEIOMhcmyoWHKulyWrqf66D3r0PaaCX537UOw9x2uWvMxsBBTrCaVtN+Rfs/3d5tTJKbd4bEC8fQICJxA=" \
            | base64 -d > android/app/my-upload-key.keystore

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build APK
        run: ${{ env.BUILD_SCRIPT }}
          
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.APK_PATH }}

